# Generated by Django 5.1.5 on 2025-01-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_genre_name_genre_genre_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_time',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
