# Generated by Django 5.1.5 on 2025-01-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_movie_country_movie_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='store.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='types',
            field=models.CharField(choices=[('144 p', '144 p'), ('360 p', '360 p'), ('480 p', '480 p'), ('720 p', '720 p'), ('1080 p', '1080 p')], default='360 p', max_length=32),
        ),
    ]
